package com.dtl.connect
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

data class Slip(val month:String,val net:String,val gross:String)
data class Doc(val title:String,val category:String,val no:String)
data class Notice(val title:String,var unread:Boolean=true)

class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{App()}}}

@Composable fun App(){var mode by remember{mutableStateOf("welcome")};when(mode){"welcome"->Welcome{mode=it};"employee"->Employee{mode="welcome"};"admin"->Admin{mode="welcome"}}}

@Composable fun Welcome(next:(String)->Unit){Column(Modifier.fillMaxSize().padding(28.dp),verticalArrangement=Arrangement.Center){Text("DTL Connect",style=MaterialTheme.typography.displaySmall);Text("Interactive v0.8 UAT Prototype");Spacer(Modifier.height(25.dp));Button({next("employee")},Modifier.fillMaxWidth()){Text("Demo Employee")};Spacer(Modifier.height(10.dp));OutlinedButton({next("admin")},Modifier.fillMaxWidth()){Text("Admin Preview")};Spacer(Modifier.height(20.dp));Text("Employee: demo.employee / DTL@Demo2026");Text("Admin: demo.admin / DTL@Admin2026")}}

@Composable fun Employee(onExit:()->Unit){var page by remember{mutableStateOf("Home")};var notices by remember{mutableStateOf(listOf(Notice("Salary slip for August 2026 is available"),Notice("APAR self-appraisal deadline: 30 Sep 2026"),Notice("New Office Order HR/2026/148 published")))};val pages=listOf("Home","Salary","Leave","Documents","Notifications","APAR","Profile");Scaffold(topBar={TopAppBar({Text("DTL Connect")},actions={TextButton(onClick=onExit){Text("Exit")}})},bottomBar={NavigationBar{pages.forEach{p->NavigationBarItem(page==p,{page=p},{},label={Text(p)})}}}){pad->Column(Modifier.padding(pad).padding(18.dp).verticalScroll(rememberScrollState())){when(page){"Home"->Home();"Salary"->Salary();"Leave"->Leave();"Documents"->Documents();"Notifications"->Notifications(notices){i->notices=notices.mapIndexed{x,n->if(x==i)n.copy(unread=false)else n}};"APAR"->Apar();"Profile"->Profile()}}}}

@Composable fun Home(){Text("Good morning, Demo Employee",style=MaterialTheme.typography.headlineSmall);Text("EMP001 • Assistant Manager • Transmission");Spacer(Modifier.height(16.dp));Card{Column(Modifier.padding(16.dp)){Text("Quick status",style=MaterialTheme.typography.titleLarge);Text("Leave: 24 days available");Text("APAR: Self-appraisal draft");Text("Latest salary: August 2026")}}}

@Composable fun Salary(){var selected by remember{mutableStateOf<Slip?>(null)};val slips=listOf(Slip("August 2026","₹82,450","₹1,18,300"),Slip("July 2026","₹81,900","₹1,17,600"),Slip("June 2026","₹81,900","₹1,17,600"));Text("Salary Slips",style=MaterialTheme.typography.headlineSmall);slips.forEach{s->Card(Modifier.fillMaxWidth().padding(vertical=5.dp),onClick={selected=s}){Column(Modifier.padding(16.dp)){Text(s.month);Text("Net ${s.net} • Gross ${s.gross}")}}};Text("Annual Salary Statement 2025-26",Modifier.padding(top=16.dp));Text("Form 16 2025-26",Modifier.padding(top=8.dp));selected?.let{s->AlertDialog({selected=null},title={Text("${s.month} Salary Slip")},text={Text("Net Pay: ${s.net}\nGross Pay: ${s.gross}\n\nSecure PDF viewer placeholder.")},confirmButton={TextButton({selected=null}){Text("Close")}})}}

@Composable fun Leave(){var show by remember{mutableStateOf(false)};var days by remember{mutableStateOf("")};Text("Leave",style=MaterialTheme.typography.headlineSmall);Text("CL 8/8 • EL 16/30 • HPL 10/20",Modifier.padding(vertical=12.dp));Button({show=true}){Text("Apply Leave")};Text("Recent applications",Modifier.padding(top=20.dp));Text("EL • 12–14 Sep • Pending");Text("CL • 21 Aug • Approved",Modifier.padding(top=8.dp));if(show)AlertDialog({show=false},title={Text("Apply Leave")},text={Column{Text("Leave type: Earned Leave");OutlinedTextField(days,{days=it},label={Text("Number of days")});Text("Reason will be mandatory in production.")}},confirmButton={TextButton({show=false}){Text(if(days.isBlank())"Save Draft" else "Submit")}})}

@Composable fun Documents(){var q by remember{mutableStateOf("")};var cat by remember{mutableStateOf("All")};val docs=listOf(Doc("HR/2026/148 — Office Order","Office Orders","HR/2026/148"),Doc("Leave Rules Manual","Manuals","HR-MAN-04"),Doc("Transfer & Posting Guidelines","Policies","HR-POL-07"));Text("Documents",style=MaterialTheme.typography.headlineSmall);OutlinedTextField(q,{q=it},label={Text("Search")},modifier=Modifier.fillMaxWidth());Row(Modifier.padding(vertical=10.dp),horizontalArrangement=Arrangement.spacedBy(5.dp)){listOf("All","Office Orders","Manuals","Policies").forEach{x->FilterChip(cat==x,{cat=x},label={Text(x)})}};docs.filter{(cat=="All"||it.category==cat)&&it.title.contains(q,true)}.forEach{d->Card(Modifier.fillMaxWidth().padding(vertical=4.dp),onClick={}){Column(Modifier.padding(16.dp)){Text(d.title);Text("${d.category} • ${d.no}");Text("Tap to open secure document",style=MaterialTheme.typography.bodySmall)}}}}

@Composable fun Notifications(items:List<Notice>,read:(Int)->Unit){Text("Notifications",style=MaterialTheme.typography.headlineSmall);items.forEachIndexed{i,n->Card(Modifier.fillMaxWidth().padding(vertical=5.dp),onClick={read(i)}){Column(Modifier.padding(16.dp)){Text(if(n.unread)"● ${n.title}" else n.title);Text(if(n.unread)"Unread" else "Read",style=MaterialTheme.typography.bodySmall)}}}}

@Composable fun Apar(){var draft by remember{mutableStateOf(true)};var text by remember{mutableStateOf("")};Text("APAR 2025-26",style=MaterialTheme.typography.headlineSmall);Text(if(draft)"Status: Draft" else "Status: Submitted");OutlinedTextField(text,{text=it},label={Text("Key achievements")},modifier=Modifier.fillMaxWidth().height(150.dp));Text("Major responsibilities",Modifier.padding(top=14.dp));OutlinedTextField("",{},label={Text("Responsibilities")},modifier=Modifier.fillMaxWidth());Row(Modifier.padding(top=14.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){Button({}){Text("Save Draft")};Button({draft=false}){Text("Submit APAR")}};Text("Employee → Reporting → Reviewing → Accepting Authority",Modifier.padding(top=14.dp))}

@Composable fun Profile(){Text("My Profile",style=MaterialTheme.typography.headlineSmall);listOf("Employee ID: EMP001","Name: Demo Employee","Designation: Assistant Manager","Department: Transmission","Office: DTL Corporate Office","Joining Date: 15 Jul 2024").forEach{Text(it,Modifier.padding(vertical=7.dp))}}

@Composable fun Admin(onExit:()->Unit){var page by remember{mutableStateOf("Dashboard")};var r by remember{mutableIntStateOf(3)};var l by remember{mutableIntStateOf(7)};var docs by remember{mutableIntStateOf(148)};val pages=listOf("Dashboard","Employees","Registrations","Salary","Leave","Documents","Notifications","APAR","Training","HR Services","Reports","Users/Roles","Audit Logs");Scaffold(topBar={TopAppBar({Text("DTL Connect — HR Admin")},actions={TextButton({onExit()}){Text("Exit")}})}){pad->Row(Modifier.padding(pad).fillMaxSize()){NavigationRail{pages.forEach{p->NavigationRailItem(page==p,{page=p},{},label={Text(p)},icon={})}};Column(Modifier.padding(20.dp).verticalScroll(rememberScrollState())){Text(page,style=MaterialTheme.typography.headlineMedium);Spacer(Modifier.height(12.dp));when(page){"Dashboard"->{Text("1,248 Active Employees");Text("$r Registration Requests");Text("$l Leave Applications Pending");Text("96% APAR Progress")};"Registrations"->{Text("$r pending registration requests");Button({if(r>0)r--}){Text("Approve next request")};OutlinedButton({}){Text("Reject / Review")}};"Leave"->{Text("$l pending leave applications");Button({if(l>0)l--}){Text("Approve next application")};OutlinedButton({}){Text("Reject")}};"Documents"->{Text("$docs published documents");Button({docs++}){Text("Publish Office Order")};Text("Secure authorization required.")};"Notifications"->{var msg by remember{mutableStateOf("")};OutlinedTextField(msg,{msg=it},label={Text("Notification message")});Button({}){Text("Broadcast to employees")}};"APAR"->{Text("2025-26 cycle • 96% submitted");Button({}){Text("View pending employees")}};else->{Text("$page module");Text("Interactive UAT foundation; production API and DTL workflow rules required.")}}}}}}}
